### ISSUE TITLE
Kein Bug - eine nette Anmerkung :)

### ISSUE THREAD

**Issue by whyisthisbroken** [TilmanGriesel/graphite#1]
Danke für das Theme, sieht gut aus.
Ich hab für mich noch folgendes noch hinzugefügt:

  # Font
  primary-font-family: 'Montserrat'
  paper-font-common-base_-_font-family: "var(--primary-font-family)"
  paper-font-common-code_-_font-family: "var(--primary-font-family)"
  paper-font-body1_-_font-family: "var(--primary-font-family)"
  paper-font-subhead_-_font-family: "var(--primary-font-family)"
  paper-font-headline_-_font-family: "var(--primary-font-family)"
  paper-font-caption_-_font-family: "var(--primary-font-family)"
  paper-font-title_-_font-family: "var(--primary-font-family)"

und unter Ressourcen folgendes:
https://fonts.googleapis.com/css2?family=Montserrat

als Stylesheet.

Sieht nun sehr elegant und edel aus. Vielen Dank :)

Vielleicht kommen ja noch ein paar Farben dazu ? Ich bin gespannt auf kommende Updates.

**Comment by TilmanGriesel** [comment]
Thanks a lot! I'm glad you like the theme and thanks for the feedback! I added the `Work Sans` font in the latest update, maybe you will like it too. My goal is to provide a very simple and clean theme which stays in the background, but I always appreciate feedback and suggestions :)

---

Vielen Dank! Freut mich sehr, dass die Theme dir gefällt und danke für die Rückmeldung! Ich habe im neuesten Update die `Work Sans` font eingebaut, vielleicht gefällt die dir auch. Mein Ziel ist es, eine sehr einfache und saubere Theme zur verfügung zu stellen, welche sich im Hintergrund hält, ich freue mich aber immer über Feedback und Anregungen :)
