### ISSUE TITLE
White color slider not visible in nest hub

### ISSUE THREAD

**Issue by maxakash** [TilmanGriesel/graphite#11]
I am casting my HA dashboard to Nest Hub 2 but white color of slider is not visible. Please look into it.
Thanks

**Comment by TilmanGriesel** [comment]
@maxakash  I apologize for the delayed response.  I will definitely have a look into it. I need some more information about the problem. Can you provide the name of the card you are using and maybe a screenshot or photo of it?

**Comment by TilmanGriesel** [comment]
Closure due to inactivity
