### ISSUE TITLE
On Android statusbar and footer (navigation area) don't have the right color

### ISSUE THREAD

**Issue by deezid** [TilmanGriesel/graphite#12]
When using the Android Home Assistant app, the navigation area and statusbar won't match the rest of dashboard using the Graphite theme while it works fine with other themes.
![Uploading Screenshot_2024-05-04-01-55-28-16_c3a231c25ed346e59462e84656a70e50.jpg…]()

**Comment by TilmanGriesel** [comment]
@deezid Thank you for your feedback! Unfortunately, the screenshot you provided is not displaying correctly. I couldn't replicate the issue on my Android tablet. Could you please re-upload the screenshot? Additionally, I've observed that a full restart of the Home Assistant Android app can sometimes resolve issues with styles not loading.

Have a nice day!

**Comment by TilmanGriesel** [comment]
Closure due to inactivity

**Comment by LordSushiPhoenix** [comment]
I have the same behavior in the dark theme on my Pixel 8 running Android 15. The status bar matches the background in light mode. Graphite v2.4.7.
![Screenshot_20241203-182916](https://github.com/user-attachments/assets/678fe1ab-1696-4b6d-8a95-507a89ea8bf7)
![Screenshot_20241203-183321](https://github.com/user-attachments/assets/df638be6-73ab-41e2-acb0-55d0bf933ce2)

**Comment by TilmanGriesel** [comment]
@deezid @LordSushiPhoenix Thank you for reporting this issue. I was finally able to pinpoint the cause and got an Android device to test it. The fix will be included in the next release, and it should work as expected.

**Comment by LordSushiPhoenix** [comment]
Brilliant, working as expected on my device.
![Screenshot_20241205-135700](https://github.com/user-attachments/assets/08fc59d8-ef90-4173-bb3f-ae630d377c76)
