### ISSUE TITLE
[FEATURE ] light proposition theme

### ISSUE THREAD

**Issue by S1M8N** [TilmanGriesel/graphite#13]
Hello,

I have a light proposition for your theme if you want you can add that for the next release 😆 : 

    light:
      token-rgb-primary: 229, 145, 9
      token-color-primary: rgb(var(--token-rgb-primary))
      token-color-accent: var(--token-color-primary)
      token-color-feedback-info: rgb(117, 47, 7)
      token-color-feedback-warning: rgb(11, 75, 255)
      token-color-feedback-error: rgb(26, 158, 127)
      token-color-feedback-success: rgb(162, 62, 110)
      token-color-icon-primary: rgba(27, 27, 24, 1)
      token-color-icon-secondary: rgb(117 115 102)
      token-color-icon-sidebar: rgba(108, 106, 96, 1)
      token-color-icon-sidebar-selected: rgba(81, 79, 72, 1)
      token-color-text-primary: rgba(27, 27, 24, 1)
      token-color-text-secondary: rgb(117 115 102)
      token-color-text-disabled: rgba(0, 0, 0, 0.5)
      token-color-text-sidebar-selected: rgba(41, 40, 36, 1)
      token-color-text-sidebar: var(--token-color-text-secondary)
      token-color-text-label-badge: rgb(57, 52, 45)
      token-color-background-base: rgba(233, 231, 226, 1)
      token-color-background-secondary: rgba(227, 226, 222, 1)
      token-color-background-sidebar: var(--token-color-background-base)
      token-color-background-input-base: rgba(209, 207, 199, 1)
      token-color-background-input-disabled: rgba(218, 218, 215, 0.5)
      token-color-background-label-badge: rgba(201, 200, 188, 1)
      token-color-background-card: rgba(218, 217, 210, 1)
      token-color-background-skrim: rgba(240, 240, 242, 0.9)
      token-color-background-divider: var(--token-color-background-sidebar)
      token-color-background-scrollbar-thumb: rgba(209, 207, 199, 1)
      token-color-background-label-badge-red: var(--token-color-feedback-error)
      token-color-background-label-badge-green: rgba(177, 72, 127, 1)
      token-color-background-label-badge-blue: var(--token-color-feedback-info)
      token-color-background-label-badge-yellow: var(--token-color-feedback-warning)
      token-color-background-label-badge-grey: rgba(172, 165, 152, 1)
      token-color-background-popup-scrim: rgba(251, 250, 248, 0.9)
      token-color-border-card: rgba(240, 240, 240, 0)

      # RGB colors
      rgb-primary-color: var(--token-rgb-primary)
      rgb-accent-color: var(--token-rgb-primary)
      rgb-white-color: 240, 243, 255
      rgb-purple-color: 189, 157, 255
      rgb-pink-color: 255, 98, 192
      rgb-red-color: 255, 97, 116
      rgb-deep-purple-color: 166, 77, 255
      rgb-indigo-color: 84, 132, 255
      rgb-blue-color: 33, 150, 243
      rgb-light-blue-color: 3, 169, 244
      rgb-cyan-color: 0, 188, 212
      rgb-teal-color: 107, 255, 237
      rgb-green-color: 141, 253, 166
      rgb-light-green-color: 156, 255, 166
      rgb-lime-color: 205, 220, 57
      rgb-yellow-color: 255, 235, 59
      rgb-amber-color: 255, 211, 99
      rgb-orange-color: var(--rgb-primary-color)
      rgb-deep-orange-color: 255, 87, 34
      rgb-brown-color: 121, 85, 72
      rgb-grey-color: 158, 158, 158
      rgb-blue-grey-color: 96, 125, 139
      rgb-black-color: 0, 0, 0
      rgb-disabled-color: 61, 65, 85
      rgb-state-inactive-color: 123, 126, 139

      # HACS
      hacs-new-color: rgb(27, 153, 123)
      hacs-error-color: rgb(182, 46, 95)

      # Editor
      codemirror-string: rgb(119, 196, 229)
      codemirror-keyword: rgb(140, 169, 255)
      codemirror-number: rgb(255, 91, 29)

      # Switch
      switch-unchecked-button-color: rgba(0, 0, 0, 0.7)
      switch-unchecked-track-color: rgba(158, 158, 158, 0.4)

      # Chip
      ha-chip-text-color: rgb(240, 240, 240)

      # Feedback colors
      error-color: rgb(234, 114, 135)
      warning-color: rgb(255, 219, 117)
      success-color: rgb(118, 214, 152)
      info-color: rgb(39, 209, 246)

**Comment by TilmanGriesel** [comment]
Hi @S1M8N, thank you for your feedback and proposal! I've been considering a light theme for a while, and your comment gave me the inspiration and motivation to finish the first revision. Your suggestion looked great and I hope you like the new light theme option. I plan to refine it further in the future based on feedback.

Have a great day!
