### ISSUE TITLE
Theme color turned gray/white after recent update

### ISSUE THREAD

**Issue by sambeetm** [TilmanGriesel/graphite#20]
![Screenshot 2024-06-10 111949](https://github.com/TilmanGriesel/graphite/assets/18508058/4f646f4e-b742-4eb0-aa8a-133b2f7ae155)

**Comment by TilmanGriesel** [comment]
@sambeetm Please ensure you select the dark theme option in your profile settings. By default, Home Assistant sets the theme to "auto," which matches your device's theme. Although I couldn't set the dark theme as the default, I wanted to make sure a light theme option is available for those who prefer it.

<img width="578" alt="image" src="https://github.com/TilmanGriesel/graphite/assets/1132745/7305b971-7885-42a3-bf48-27fa9fafc763">

**Comment by ineedhungry** [comment]
This wasn't like this before.  Isn't the point of having a graphite theme to be static, not auto?  This hinders certain dashboards from having one look over another.

**Comment by sambeetm** [comment]
I have 6 dashboards. 3 are using graphite. Setting the profile to Dark, causing unintended look to other 3 dashboards and the default browser also goes to dark.Meanwhile, I have downgraded to 2.1 stay at 2.1 until there is a better solution.On Jun 11, 2024, at 11:24 AM, ineedhungry ***@***.***> wrote:﻿
This wasn't like this before.  Isn't the point of having a graphite theme to be static, not auto?  This hinders certain dashboards from having one look over another.

**Comment by TilmanGriesel** [comment]
@sambeetm @ineedhungry Thank you for your feedback and for clarifying your use case. I will split the themes into two to accommodate those use cases and to avoid any further confusion.

**Comment by TilmanGriesel** [comment]
@sambeetm @ineedhungry Please update to version 2.2.3 when it becomes available. The light theme is now separated into its own file. We hope this resolves any issues 🙂  https://github.com/TilmanGriesel/graphite/releases/tag/2.2.3

**Comment by sambeetm** [comment]
Will do. Thank you for the Fix! Highly appreciated.On Jun 11, 2024, at 12:16 PM, Tilman Griesel ***@***.***> wrote:﻿
@sambeetm @ineedhungry Please update to version 2.2.3 when it becomes available. The light theme is now separated into its own file. We hope this resolves any issues 🙂  https://github.com/TilmanGriesel/graphite/releases/tag/2.2.3

**Comment by karolpela** [comment]
@TilmanGriesel Splitting the theme into two files disables the option to have it switch automatically based on the OS color mode. Personally, I prefer using a light theme during the day and a dark theme during the night.
Since Home Assistant offers a mechanism for setting Dark/Light/Auto, I think it should remain functional.

I realize this might be inconvenient for the abovementioned use-cases, but they do seem to be edge cases - requiring an approach different than the HA's default one.

**Comment by TilmanGriesel** [comment]
@karolpela I believe it's feasible to create a combined theme, but I'd like to implement it through CI to ensure both themes stay in sync and avoid divergence. As a first step, I can manually merge the themes and name it something like 'Graphite-Auto' or similar.
