### ISSUE TITLE
Back button not working

### ISSUE THREAD

**Issue by Phantomx2** [TilmanGriesel/graphite#31]
Go to settings -> devices & services -> integrations -> enter any integrations
Press the back button in top left
Notice it's not doing anything

This is not happening using a different theme.

**Comment by TilmanGriesel** [comment]
Hello @Phantomx2,

I have not been able to reproduce the issue of the back button not working in the integration view. Normally themes do not affect such features, so it is somewhat unusual for this behavior to occur.

To help me troubleshoot, could you please give us some additional details?

1. **Version of Home Assistant**
1. **Operating system**
1. **Device**
1. **Browser**
1. **Custom themes or add-ons**

**Comment by Phantomx2** [comment]
I closed the issue as it seems to have resolved itself, doesn't happen anymore for me either.
Thanks

**Comment by TilmanGriesel** [comment]
Perfect! 👍  Good to hear that it was a temporary issue.
