### ISSUE TITLE
Top header row padding visible with HA 2024.11.x when using HACS Kiosk-Mode integration

### ISSUE THREAD

**Issue by NathanVanCleave** [TilmanGriesel/graphite#32]
I am using the [Kiosk-Mode](https://github.com/NemesisRE/kiosk-mode) integration to remove the top header row on my dashboards. After updating HA from 2024.10.x to 2024.11.x the padding for the header row remains when using the Graphite theme. 
<img width="531" alt="Screenshot 2024-11-08 at 9 58 23 PM" src="https://github.com/user-attachments/assets/40160daf-5ff1-4589-a32d-bc225a8ae9b6">
<img width="542" alt="Screenshot 2024-11-08 at 9 58 11 PM" src="https://github.com/user-attachments/assets/5e822d41-7a37-452a-8b03-74378a7996b8">

An [issue](https://github.com/NemesisRE/kiosk-mode/issues/295) was opened on that repo and [someone found](https://github.com/NemesisRE/kiosk-mode/issues/295#issuecomment-2465410692) that some themes treat the top padding differently. An issue was opened on that particular theme's repo and the author [looks to have added a fix](https://github.com/Nerwyn/material-rounded-theme/issues/44#issuecomment-2465945900).

Just wanted to bring this to your attention. I could play around myself but I don't really know what I'm doing.

Thanks!

**Comment by TilmanGriesel** [comment]
@NathanVanCleave Thanks for the report! I will have a look into it soon. Should be fixable 👍

**Comment by TilmanGriesel** [comment]
Hi @NathanVanCleave, just a quick update: I haven't been able to reproduce the issue on my end so far. Could you share more details about your configuration?

**Comment by NathanVanCleave** [comment]
It looks like it might actually be something that [can be fixed in Kiosk-Mode](https://github.com/NemesisRE/kiosk-mode/issues/295#issuecomment-2466978652). I haven't tested it yet but will report back when I do.

**Comment by TilmanGriesel** [comment]
@NathanVanCleave @pskowronek mentioned it works properly now 🎉 https://github.com/NemesisRE/kiosk-mode/issues/295#issuecomment-2467822448

**Comment by NathanVanCleave** [comment]
Yup! Might have jumped the gun a bit creating an issue here, but I really appreciate your speedy attention!

Everything is working just fine now on 2024.11.x

**Comment by NathanVanCleave** [comment]
Yup! Might have jumped the gun a bit creating an issue here, but I really appreciate your speedy attention!

Everything is working just fine now on 2024.11.x
