### ISSUE TITLE
Choose label button has dark background and dark text.

### ISSUE THREAD

**Issue by lwsrbrts** [TilmanGriesel/graphite#51]
**Bug Report**  
---

### **Quick Checklist**  
- [x] I am using the latest version of Home Assistant.  
- [x] I cleared my browser cache.  
- [x] I checked the [documentation](https://www.home-assistant.io/help/reporting_issues/) and existing issues.  

---

### **Details**  

**Home Assistant Version:**  
2024.11.3

**Last Known Working Version (if any):**  
None

**Browser & OS:**  
Everything but I mainly use Firefox.

**Plugins etc.:**  
 * Mushroom 4.2
 * card-mod 3.4.3

---

### **The Problem**  
Earlier this year `labels` were introduced and as a result, a new button on things like Developer Tools as well as the History etc. For me, the `Choose label` button has always displayed as a very dark background with dark text. Screenshot below

---

### **Steps to Reproduce**  

1. In Developer Tools, select an Action and ensure the GUI is visible.
2. The `Choose label` button has a dark background but also dark text.

---

### **Additional Information**  
This is how it looks to me. This is just one example, The History section's `Choose label` button would look the same also.

![2024-11-30 10_18_57-Developer Tools – Home Assistant — Mozilla Firefox](https://github.com/user-attachments/assets/b991b0a7-5bbc-48eb-a717-6c08848430ec)

I went looking for the issue and discovered that commenting out line #546 in Graphite Auto resolved the issue for me. Clearly I don't know everywhere in the theme this would be used but I've not spotted anything negative happen as a result.

The screenshot below is a result of commenting out line #546 in `graphite-auto.yaml`

![2024-11-30 10_18_44-Developer Tools – Home Assistant — Mozilla Firefox](https://github.com/user-attachments/assets/3fd00b7d-1f97-431a-a2ab-ddc8927ac6ee)

**Comment by lwsrbrts** [comment]
Missed one screenshot showing which line is commented specifically.
![2024-11-30 10_37_41-Studio Code Server – Home Assistant — Mozilla Firefox](https://github.com/user-attachments/assets/60f8291a-fef3-4180-9fbc-4be1525df903)

**Comment by TilmanGriesel** [comment]
Thank you for your report and detailed issue description, @lwsrbrts! I was able to reproduce the issue as well as your proposed fix. Based on my testing, removing the assignment doesn't appear to cause any other problems. It seems likely that something has changed under the hood on the Home Assistant side. I'll release a pre-release version with the key removed, but let's all keep an eye out for any unintended side effects 👀.

**Comment by TilmanGriesel** [comment]
Pre-release is out: https://github.com/TilmanGriesel/graphite/releases/tag/2.4.5
