### ISSUE TITLE
Allow new tokens in Theme Patcher

### ISSUE THREAD

**Issue by IzeQube** [TilmanGriesel/graphite#60]
**Feature Request**  
It would be great if I could add new tokens to the theme with the Theme Patcher.

---

### **Opportunity or Improvement**  
I just found this theme but am using Bubble Cards in my main dashboard. Bubble card now supports quite a few variables, but none of them seem to be the "normal" well known theme variables.

If I can use the patcher to add new variables to the theme I won't have to form this project.

---

### **Proposed Solution**  
Add variables if the don't exist in the theme.

---

### **Alternatives or Ideas**  
Support bubble theme officially :-)

---

### **Extra Details**  
./.

---

**Comment by TilmanGriesel** [comment]
@IzeQube Thanks for the great idea! I've implemented a solution for you - using the `--create` argument will now create the entry if it doesn't exist. This is a versatile first step.

I do plan to officially integrate the Bubble Cards, but with my limited time, my primary focus is on supporting the base theme as thoroughly as possible. That said, I'm curious what specific variable modifications for the Bubble Card are you most interested in? I'd love to gather input on the most requested variables to prioritize future updates.

**Comment by TilmanGriesel** [comment]
Get the latest version via: https://graphite.tilmangriesel.com/features/graphite-theme-patcher.html#installation

**Comment by IzeQube** [comment]
@TilmanGriesel thank you.

I think it isn't working right because the indentation is missing when a new value is added which breaks the theme file:
![image](https://github.com/user-attachments/assets/5653f270-9446-4945-b8f9-0d9b1d1d4f48)

Also there is a error on the documentation now. In the [block](https://graphite.tilmangriesel.com/features/graphite-theme-patcher.html#advanced-shell-command-example) the shell_command includes the path to your dev environment.

**Comment by TilmanGriesel** [comment]
@IzeQube You're absolutely right! Thank you for testing it. I jumped the gun there a bit, but I've now corrected the patcher to accommodate the indentation level. It was a bit trickier than expected.

**Comment by TilmanGriesel** [comment]
Thanks for pointing out the oversight in the documentation! I've moved a lot of things around in this project over the past few weeks and definitely should have done a more thorough review.

**Comment by IzeQube** [comment]
@TilmanGriesel brilliant, it seems to be working now. Thanks for you quick fix.

Now I'll have to look what looks good with your theme and bubble card.

**Comment by TilmanGriesel** [comment]
@IzeQube You got it! Thank you, and have fun tinkering with it!

**Comment by NeeeeB** [comment]
@IzeQube 
I'm trying to achieve the same thing in HA, but it does not work for me...
Any help would be greatly appreciated.
This is what my script looks like :
![image](https://github.com/user-attachments/assets/2a8a717f-6d21-4282-a9b5-d830d1779d2e)
and this is the error HA is throwing : 
![image](https://github.com/user-attachments/assets/1b741e43-74c6-4512-bf22-10cb906319de)

I've also tested with something more "simple" just to see : 
![image](https://github.com/user-attachments/assets/1155daf1-f002-4560-9bc4-8043362c5f6b)
This time I get no error in HA, but that test token is not added to the graphite.yaml file...

PS: this is what my shell commands looks like : 
![image](https://github.com/user-attachments/assets/f68d8ed3-eef3-49e7-a0c1-6157d304979b)

Many thanks for any help you could provide.
