### ISSUE TITLE
Inhomogeneous RGB colors "units" in theme gives issue in Theme Patcher

### ISSUE THREAD

**Issue by Wendigogo** [TilmanGriesel/graphite#66]
I guess all above isn't relevant here.

### **The Problem**  
In graphite.yaml, some color tokens are in rgb format with only RGB values (ie : `token-rgb-primary: 28, 113, 216`) and some required a `rgb` or `rgba` string (ie : `token-color-text-primary: rgb(228, 228, 231)`).

So when using these tokens in Theme Patcher, it removes these `rgb` or `rgba` string (ie : `token-color-text-primary: 228, 228, 231`) which leads to an issue.

Is it possible to remove all `rgb` or `rgba` references in the theme yaml so the Theme Patcher could be used with all tokens please?

Or, easier I guess, give an example on how to add these strings (and latest `)` ) in Theme Patcher examples.

Thanks a lot for your help.

**Comment by TilmanGriesel** [comment]
@Wendigogo Thanks for the report, great catch! The theme patcher was originally designed to handle the primary color as a simple, comma-separated list of color component values. However, it didn't yet support more complex CSS syntax tokens. Based on your feedback, I'll update it to include support for CSS color tokens with alpha channel values.

**Comment by TilmanGriesel** [comment]
Please pull the latest patcher version 1.3.0 via:
`wget -O /config/scripts/graphite-theme-patcher.py https://raw.githubusercontent.com/TilmanGriesel/graphite/refs/heads/main/extras/theme-patcher/graphite-theme-patcher.py`

**Comment by Wendigogo** [comment]
Tested and working : `token-color-text-secondary: rgb(255, 128, 64)  # Modified via Graphite Theme Patcher v1.3.0 - 2024-12-12 18:25:40`

Thanks a lot !
