### ISSUE TITLE
Clock card

### ISSUE THREAD

**Issue by Liborsaf** [TilmanGriesel/graphite#9]
Great clean theme! Can you please share your clock card config?

**Comment by TilmanGriesel** [comment]
@Liborsaf, thank you, and I apologize for the delayed response. 🙏 I very much appreciate your feedback.

Absolutely! The custom cards you will need are [lovelace-digital-clock](https://github.com/wassy92x/lovelace-digital-clock) and [lovelace-card-mod](https://github.com/thomasloven/lovelace-card-mod) — you can get them both on HACS. 

Here’s my card configuration:

```
type: custom:digital-clock
locale: de
dateFormat:
  weekday: long
  day: 2-digit
  month: long
timeFormat:
  hour: 2-digit
  minute: 2-digit
card_mod:
  style: |
    ha-card {
      padding: 16px 0 !important;
    }
    .first-line {
      font-weight: 600 !important;
      font-size: 32px !important;
      color: var(--primary-text-color) !important;
    }
    .second-line {
      font-weight: 500 !important;
      font-size: 16px !important;
      color: var(--secondary-text-color) !important;
    }
```
